# Generated by Django 4.1.7 on 2023-02-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Yield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plz", models.CharField(max_length=5)),
                ("pv_yield", models.FloatField()),
            ],
        ),
    ]
